---
os: linux
dist: bionic
language: python
cache:
  directories:
    - $HOME/.vagrant.d/boxes/
env:
  - BOX: ubuntu/focal64
  - BOX: ubuntu/bionic64
  - BOX: ubuntu/xenial64
  - BOX: debian/buster64
install:
  - SCRIPTS_BASE_URL=https://raw.githubusercontent.com/sprat/install-scripts/master
  - wget -qO- ${SCRIPTS_BASE_URL}/install_virtualbox.sh | sudo bash
  - wget -qO- ${SCRIPTS_BASE_URL}/install_hashicorp_packages.sh | sudo bash -s vagrant
  - pip install -Ur requirements.in
script:
  - molecule --version
  - molecule -v test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
