---
- name: Converge
  hosts: all
  vars:
    grub_d_files:
      98-audit:  # file to remove
      99-docker:
        GRUB_CMDLINE_LINUX_DEFAULT: $GRUB_CMDLINE_LINUX_DEFAULT cgroup_enable=memory swapaccount=1

  roles:
    - role: ansible-role-grub
