---
name: CI
"on":
  push:
  schedule:
    - cron: "0 2 * * 1"

jobs:
  # test the role
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        box:
          - ubuntu/focal64
          - ubuntu/bionic64
          - ubuntu/xenial64
          - debian/buster64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.in

      - name: Run molecule tests
        env:
          BOX: ${{ matrix.box }}
        run: molecule -v test

  # publish the role on ansible galaxy
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
