---
name: main
"on": push

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        box:
          - ubuntu/focal64
          - ubuntu/bionic64
          - ubuntu/xenial64
          - debian/buster64
    env:
      BOX: ${{ matrix.box }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.in
      - run: molecule -v test
